# Generated by Django 4.1 on 2023-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keword', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.URLField()),
                ('description', models.TextField()),
                ('source_link', models.CharField(max_length=100)),
                ('source_website', models.URLField()),
                ('company_email', models.CharField(max_length=100)),
                ('company_phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
