# Generated by Django 4.2.1 on 2023-05-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navigator_link", models.CharField(default=None, max_length=1000)),
                ("no_of_leads", models.CharField(default=None, max_length=100)),
                ("status", models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
